zip -r -p "LJLogM_v1.09.zip" ".\LJLogM.exe")
zip -r -p "LJLogM_v1.09.zip" ".\LJLogM.ini")
zip -r -p "LJLogM_v1.09.zip" ".\release.bat")
zip -r -p "LJLogM_v1.09.zip" ".\install.bat")
zip -r -p "LJLogM_v1.09.zip" ".\install-multiple-instances.bat")